Repository python-poetry/poetry, pull requests merged in 2019-08, with the labels that each got.

#1260 Add support for url dependencies
  docs/docs/versions.md
  poetry/console/commands/add.py
  poetry/console/commands/init.py
  poetry/json/schemas/poetry-schema.json
  poetry/packages/__init__.py
  poetry/packages/dependency.py
  poetry/packages/package.py
  poetry/packages/url_dependency.py
  poetry/puzzle/provider.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pypi_repository.py
  poetry/utils/inspector.py
  tests/conftest.py
  tests/console/commands/test_add.py
  tests/console/conftest.py
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/test_installer.py
  tests/masonry/builders/fixtures/with_url_dependency/pyproject.toml
  tests/masonry/builders/fixtures/with_url_dependency/with_url_dependency/__init__.py
  tests/masonry/builders/test_builder.py
Labels: CLI, Feature, Installation

#1272 Improve the way settings are managed
  .gitignore
  docs/docs/configuration.md
  docs/docs/repositories.md
  poetry/config.py
  poetry/config/__init__.py
  poetry/config/config.py
  poetry/config/config_source.py
  poetry/console/commands/config.py
  poetry/masonry/publishing/publisher.py
  poetry/poetry.py
  poetry/utils/env.py
  poetry/utils/helpers.py
  poetry/utils/toml_file.py
  tests/config/__init__.py
  tests/config/test_config.py
  tests/conftest.py
  tests/console/commands/env/test_list.py
  tests/console/commands/env/test_remove.py
  tests/console/commands/env/test_use.py
  tests/console/commands/test_config.py
  tests/console/conftest.py
  tests/fixtures/with_local_config/README.rst
  tests/fixtures/with_local_config/poetry.toml
  tests/fixtures/with_local_config/pyproject.toml
  tests/masonry/publishing/test_publisher.py
  tests/test_config.py
  tests/test_poetry.py
  tests/utils/test_env.py
  tests/utils/test_helpers.py
  tests/utils/test_helpers_keyring.py
Labels: CLI, Configuration, Feature

#1275 Add support for PyPI API tokens
  docs/docs/repositories.md
  poetry/console/commands/config.py
  poetry/console/commands/publish.py
  poetry/masonry/publishing/publisher.py
  tests/console/commands/test_config.py
  tests/masonry/publishing/test_publisher.py
Labels: Configuration, Feature, Publishing

#1277 Improve the export command
  docs/docs/cli.md
  poetry/console/commands/export.py
  poetry/packages/dependency.py
  poetry/utils/exporter.py
  tests/utils/test_exporter.py
Labels: CLI, Feature

#945 fix typo in doc site
  docs/docs/pyproject.md
Labels: Documentation

#1309 950 simplified
  poetry/masonry/builders/wheel.py
  tests/masonry/builders/fixtures/localversionlabel/localversionlabel.py
  tests/masonry/builders/fixtures/localversionlabel/pyproject.toml
  tests/masonry/builders/test_wheel.py
Labels: Bug

#1320 remove NoReturn, use None instead
  poetry/utils/helpers.py
Labels: Documentation

#1324 Check to ensure the global config exists before reading
  poetry/console/commands/config.py
Labels: Bug

#1326 Fix pytest fixtures on Win10
  tests/conftest.py
  tests/console/conftest.py
Labels: Testing
