Repository python-poetry/poetry, pull requests merged in 2019-10, with the labels that each got.

#1236 Use `os.execvp` for `poetry run`
  poetry/console/commands/run.py
  poetry/utils/env.py
Labels: Feature

#1341 Add support for special characters in username/password for pip
  poetry/repositories/legacy_repository.py
  tests/repositories/test_legacy_repository.py
Labels: Bug

#1430 Fix console output render for show command
  poetry/console/commands/show.py
Labels: Bug

#1294 export: fix exporting extras sub-dependencies
  poetry/installation/installer.py
  poetry/utils/exporter.py
  poetry/utils/extras.py
  tests/utils/test_exporter.py
  tests/utils/test_extras.py
Labels: Bug

#794 Support POETRY_HOME for install
  CHANGELOG.md
  docs/docs/index.md
  get-poetry.py
Labels: Feature

#1408 Fixes error messages that point to list items
  poetry/json/__init__.py
Labels: Bug

#1337 Resolve git refs to git revisions [#1331]
  poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: Bug

#1460 Improve files metadata in lock files
  poetry.lock
  poetry/installation/pip_installer.py
  poetry/packages/locker.py
  poetry/packages/package.py
  poetry/puzzle/provider.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pypi_repository.py
  poetry/utils/exporter.py
  pyproject.toml
  tests/installation/fixtures/extras-with-dependencies.test
  tests/installation/fixtures/extras.test
  tests/installation/fixtures/install-no-dev.test
  tests/installation/fixtures/no-dependencies.test
  tests/installation/fixtures/remove.test
  tests/installation/fixtures/update-with-lock.test
  tests/installation/fixtures/update-with-locked-extras.test
  tests/installation/fixtures/with-category-change.test
  tests/installation/fixtures/with-conditional-dependency.test
  tests/installation/fixtures/with-dependencies-extras.test
  tests/installation/fixtures/with-dependencies.test
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/installation/fixtures/with-directory-dependency-setuptools.test
  tests/installation/fixtures/with-duplicate-dependencies-update.test
  tests/installation/fixtures/with-duplicate-dependencies.test
  tests/installation/fixtures/with-file-dependency-transitive.test
  tests/installation/fixtures/with-file-dependency.test
  tests/installation/fixtures/with-multiple-updates.test
  tests/installation/fixtures/with-optional-dependencies.test
  tests/installation/fixtures/with-platform-dependencies.test
  tests/installation/fixtures/with-prereleases.test
  tests/installation/fixtures/with-pypi-repository.test
  tests/installation/fixtures/with-python-versions.test
  tests/installation/fixtures/with-sub-dependencies.test
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/fixtures/with-wheel-dependency-no-requires-dist.test
  tests/installation/test_pip_installer.py
  tests/packages/test_locker.py
  tests/repositories/test_legacy_repository.py
Labels: Feature

#787 Fix PATH being altered after installation even though choose not to
  get-poetry.py
Labels: Bug

#1291 Clarify search for package command usage
  poetry/console/commands/init.py
Labels: Documentation

#1461 provider:search_for_directory - set package.root_dir
  poetry/puzzle/provider.py
  tests/puzzle/test_provider.py
Labels: Bug, Hacktoberfest

#1477 Improve environment management
  poetry/console/commands/debug/resolve.py
  poetry/console/commands/env/info.py
  poetry/console/commands/env/list.py
  poetry/console/commands/env/remove.py
  poetry/console/commands/env/use.py
  poetry/console/commands/init.py
  poetry/console/config/application_config.py
  poetry/packages/package.py
  poetry/puzzle/provider.py
  poetry/utils/env.py
  poetry/utils/helpers.py
  tests/console/commands/env/test_list.py
  tests/console/commands/env/test_remove.py
  tests/console/commands/env/test_use.py
  tests/masonry/builders/test_builder.py
  tests/masonry/builders/test_complete.py
  tests/masonry/test_api.py
  tests/puzzle/test_provider.py
  tests/test_factory.py
  tests/utils/test_env.py
Labels: CLI, Feature

#1432 Detect Conda when looking for a virtual env
  poetry/utils/env.py
Labels: Feature, Virtualenvs

#1482 Fix dependency resolution for conditional development dependencies
  poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: Bug

#1464 Exclude nested items (#784)
  poetry/masonry/builders/builder.py
  tests/masonry/builders/fixtures/exclude_nested_data_toml/LICENSE
  tests/masonry/builders/fixtures/exclude_nested_data_toml/README.rst
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/__init__.py
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/data/data1.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/data/sub_data/data2.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/data/sub_data/data3.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/puplic/item1/itemdata1.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/puplic/item1/subitem/subitemdata.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/puplic/item2/itemdata2.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/puplic/publicdata.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/pyproject.toml
  tests/masonry/builders/test_sdist.py
  tests/masonry/builders/test_wheel.py
Labels: Feature, Hacktoberfest

#1325 Add support for custom certificate authority and client certificates
  .pre-commit-config.yaml
  docs/docs/repositories.md
  poetry/console/commands/config.py
  poetry/console/commands/publish.py
  poetry/factory.py
  poetry/installation/pip_installer.py
  poetry/masonry/publishing/publisher.py
  poetry/masonry/publishing/uploader.py
  poetry/repositories/legacy_repository.py
  poetry/utils/helpers.py
  tests/console/commands/test_config.py
  tests/console/commands/test_publish.py
  tests/installation/test_pip_installer.py
  tests/masonry/publishing/test_publisher.py
  tests/utils/test_helpers.py
Labels: Feature
