Repository python-poetry/poetry, pull requests merged in 2019-09, with the labels that each got.

#1344 Improve documentation
  docs/docs/cli.md
  docs/docs/configuration.md
  docs/docs/contributing.md
Labels: Documentation

#1343 Update README for pipenv command name
  README.md
Labels: Documentation

#1347 Setup CI with Github Actions
  .appveyor.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  .travis.yml
  tests/masonry/builders/test_complete.py
Labels: Testing

#1129 Fix METADATA generation for git dependencies with extras
  poetry/packages/dependency.py
  tests/packages/test_vcs_dependency.py
Labels: Bug, Packaging

#1306 Fix support for url sourced packages in pip installer
  poetry/installation/pip_installer.py
  tests/installation/test_pip_installer.py
Labels: Bug

#1322 Fix file installation for wheels with no Requires-Dist
  poetry/utils/inspector.py
  tests/fixtures/wheel_with_no_requires_dist/demo-0.1.0-py2.py3-none-any.whl
  tests/installation/fixtures/with-wheel-dependency-no-requires-dist.test
  tests/installation/test_installer.py
Labels: Bug

#1266 Add make targets
  Makefile
Labels: Testing

#1271 Housekeeping on tests/conftest.py
  tests/conftest.py
Labels: Refactor, Testing

#1346 Fix ValueError when finding packages with invalid metadata
  poetry/repositories/pypi_repository.py
  tests/repositories/fixtures/pypi.org/json/pygame-music-grid.json
  tests/repositories/test_pypi_repository.py
Labels: Bug

#1349 Refactor the internal code base
  poetry/config/config.py
  poetry/config/config_source.py
  poetry/config/dict_config_source.py
  poetry/config/file_config_source.py
  poetry/console/application.py
  poetry/console/commands/check.py
  poetry/console/commands/config.py
  poetry/factory.py
  poetry/masonry/api.py
  poetry/masonry/builders/complete.py
  poetry/poetry.py
  poetry/puzzle/provider.py
  tests/config/test_config.py
  tests/conftest.py
  tests/console/commands/test_check.py
  tests/console/commands/test_config.py
  tests/console/commands/test_export.py
  tests/console/conftest.py
  tests/masonry/builders/test_builder.py
  tests/masonry/builders/test_complete.py
  tests/masonry/builders/test_editable.py
  tests/masonry/builders/test_sdist.py
  tests/masonry/builders/test_wheel.py
  tests/masonry/publishing/test_publisher.py
  tests/masonry/publishing/test_uploader.py
  tests/test_factory.py
  tests/utils/test_exporter.py
Labels: Refactor

#1327 Enforce package name for poetry projects from directory source
  poetry/puzzle/provider.py
  tests/console/commands/test_add.py
  tests/puzzle/test_provider.py
Labels: Bug

#1398 Improve issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---documentation.md
  .github/ISSUE_TEMPLATE/---everything-else.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/2_Feature_request.md
Labels: Documentation

#1399 Fix small typos, missing header, and add label to Documentation.
  .github/ISSUE_TEMPLATE/---documentation.md
  .github/ISSUE_TEMPLATE/---everything-else.md
  .github/ISSUE_TEMPLATE/---feature-request.md
Labels: Documentation

#1374 Improve command-line descriptions
  poetry/console/commands/add.py
  poetry/console/commands/build.py
  poetry/console/commands/cache/clear.py
  poetry/console/commands/config.py
  poetry/console/commands/debug/resolve.py
  poetry/console/commands/init.py
  poetry/console/commands/install.py
  poetry/console/commands/new.py
  poetry/console/commands/remove.py
  poetry/console/commands/script.py
  poetry/console/commands/search.py
  poetry/console/commands/self/update.py
  poetry/console/commands/show.py
  poetry/console/commands/update.py
Labels: CLI, Documentation

#1305 Use canonical name when validating package from directory
  poetry/puzzle/provider.py
  tests/fixtures/git/github.com/demo/non-canonical-name/demo/__init__.py
  tests/fixtures/git/github.com/demo/non-canonical-name/setup.py
  tests/puzzle/test_provider.py
Labels: Bug

#1321 Ensure develop flag is respected for git packages
  poetry/installation/pip_installer.py
  tests/installation/test_pip_installer.py
Labels: Bug

#1397 docs: Specify Python versions using double pipe
  docs/docs/versions.md
Labels: Documentation

#1395 Improve the shell command
  poetry.lock
  poetry/console/commands/shell.py
  poetry/utils/shell.py
  pyproject.toml
Labels: Bug, CLI
