Repository python-poetry/poetry, pull requests merged in 2019-11, with the labels that each got.

#1549 Improve git dependencies support
  .gitignore
  .pre-commit-config.yaml
  docs/docs/cli.md
  poetry.lock
  poetry/console/commands/init.py
  poetry/puzzle/solver.py
  poetry/repositories/installed_repository.py
  poetry/utils/env.py
  poetry/vcs/git.py
  pyproject.toml
  tests/console/commands/test_add.py
  tests/console/conftest.py
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/cleo-0.7.6.dist-info/METADATA
  tests/repositories/fixtures/installed/src/pendulum/pendulum.egg-info/PKG-INFO
  tests/repositories/fixtures/installed/src/pendulum/pendulum.egg-info/requires.txt
  tests/repositories/test_installed_repository.py
  tests/vcs/__init__.py
  tests/vcs/test_git.py
Labels: Bug, Feature

#1555 Fix handling of extra markers
  poetry/puzzle/solver.py
  poetry/version/markers.py
  tests/puzzle/test_solver.py
Labels: Bug

#1576 Fix invalid git url errors
  poetry/puzzle/solver.py
  tests/puzzle/test_solver.py
Labels: Bug

#1577 Fix support for egg files in InstalledRepository
  .gitignore
  poetry/repositories/installed_repository.py
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/foo-0.1.0-py3.8.egg
  tests/repositories/test_installed_repository.py
Labels: Bug

#694 Add a Code of Conduct
  CODE_OF_CONDUCT.md
Labels: Documentation

#1591 CHANGE: simplified output by `poetry version`
  poetry/console/commands/version.py
  tests/console/commands/test_version.py
Labels: CLI

#861 Commonize pip running logic and use system pip in system env
  poetry/installation/pip_installer.py
  poetry/masonry/builders/editable.py
  poetry/utils/env.py
  tests/masonry/builders/test_editable.py
Labels: Bug

#1607 Fix an error in show when using the -o option
  poetry/console/commands/show.py
  tests/console/commands/test_show.py
Labels: Bug
