Repository python-poetry/poetry, pull requests merged in 2019-12, with the labels that each got.

#1041 added install instruction for powershell users
  docs/docs/index.md
Labels: Documentation

#1683 Improve the site-packages directory detection
  poetry/utils/env.py
  tests/utils/test_env.py
Labels: Virtualenvs

#1687 Release 1.0.0b9
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#1712 Update docs about `self update`syntax
  README.md
  docs/docs/index.md
Labels: Documentation

#1722 fix: change `self:uninstall` to `self uninstall` in `get-poetry.py`
  get-poetry.py
Labels: Documentation

#1673 Removing setecho(False) for all shells
  poetry/utils/shell.py
Labels: Bug

#1750 fix: don't exclude files that are explicit included in wheel (#1336)
  poetry/masonry/builders/wheel.py
  tests/masonry/builders/fixtures/exclude_nested_data_toml/my_package/data/data2.txt
  tests/masonry/builders/fixtures/exclude_nested_data_toml/pyproject.toml
  tests/masonry/builders/test_sdist.py
  tests/masonry/builders/test_wheel.py
Labels: Bug

#1756 fix (git.py): git url's can now contain longer path names (#1746)
  poetry/vcs/git.py
  tests/vcs/test_git.py
Labels: Bug

#1774 Correctly handle spaces in command executable
  poetry/utils/env.py
Labels: Bug

#1784 Fix link to env variables configuration reference
  docs/docs/repositories.md
Labels: Documentation

#1800 fix (cli.md): there is no `poetry list` command
  docs/docs/cli.md
Labels: Documentation
