Repository python-poetry/poetry, pull requests merged in 2020-09, with the labels that each got.

#2743 use ZSH_CUSTOM
  README.md
  docs/docs/index.md
Labels: Documentation

#2820 Update release script to support freebsd builds
  make-nix-release.sh
Labels: Bug

#2906 Improve performance of package ordering/tagging after version solving
  poetry/puzzle/solver.py
  tests/puzzle/test_solver.py
Labels: Dependency resolution, Improvement

#2928 Ensure retry logic does not fail on empty io
  poetry/installation/authenticator.py
Labels: Bug

#2887 Fix and improve handling of extras while resolving dependencies
  poetry.lock
  poetry/console/commands/debug/resolve.py
  poetry/console/commands/init.py
  poetry/console/commands/show.py
  poetry/factory.py
  poetry/inspection/info.py
  poetry/installation/executor.py
  poetry/installation/pip_installer.py
  poetry/mixology/incompatibility.py
  poetry/mixology/partial_solution.py
  poetry/mixology/term.py
  poetry/mixology/version_solver.py
  poetry/packages/dependency_package.py
  poetry/packages/locker.py
  poetry/packages/package_collection.py
  poetry/puzzle/provider.py
  poetry/puzzle/solver.py
  poetry/repositories/base_repository.py
  poetry/repositories/installed_repository.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pool.py
  poetry/repositories/pypi_repository.py
  poetry/repositories/repository.py
  poetry/utils/exporter.py
  poetry/utils/helpers.py
  poetry/version/version_selector.py
  pyproject.toml
  tests/console/commands/debug/test_resolve.py
  tests/console/commands/test_add.py
  tests/console/commands/test_show.py
  tests/console/conftest.py
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/installation/fixtures/with-directory-dependency-setuptools.test
  tests/installation/fixtures/with-file-dependency-transitive.test
  tests/installation/fixtures/with-file-dependency.test
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/fixtures/with-wheel-dependency-no-requires-dist.test
  tests/installation/test_chooser.py
  tests/installation/test_executor.py
  tests/installation/test_installer.py
  tests/installation/test_installer_old.py
  tests/installation/test_pip_installer.py
  tests/mixology/helpers.py
  tests/mixology/version_solver/test_backtracking.py
  tests/mixology/version_solver/test_basic_graph.py
  tests/mixology/version_solver/test_python_constraint.py
  tests/mixology/version_solver/test_unsolvable.py
  tests/mixology/version_solver/test_with_lock.py
  tests/packages/test_locker.py
  tests/puzzle/test_provider.py
  tests/puzzle/test_solver.py
  tests/repositories/test_installed_repository.py
  tests/repositories/test_legacy_repository.py
  tests/repositories/test_pypi_repository.py
  tests/test_factory.py
  tests/utils/test_env.py
  tests/utils/test_exporter.py
  tests/utils/test_extras.py
Labels: Dependency resolution

#2935 Release 1.1.0b3
  CHANGELOG.md
  poetry.lock
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2941 Fix inconsistencies with release scripts
  .cirrus.yml
  .github/workflows/main.yml
  make-nix-release.sh
  poetry/installation/executor.py
  sonnet
Labels: Bug, Packaging

#2948 Bump version to 1.1.0b4
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2954 provider: ensure download dest file is a string
  poetry/puzzle/provider.py
Labels: Bug

#2577 Add log warning if auth fails when accessing repository
  poetry/repositories/legacy_repository.py
Labels: Error Handling

#2971 Release 1.1.0rc1
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2957 Fix cases where poetry should fall back to pep517 metadata parsing
  poetry/inspection/info.py
  poetry/utils/setup_reader.py
  tests/inspection/test_info.py
  tests/utils/fixtures/setups/with-setup-cfg-attr/setup.cfg
  tests/utils/fixtures/setups/with-setup-cfg-attr/setup.py
  tests/utils/test_setup_reader.py
Labels: Bug

#2987 Change documentation of path dependency
  docs/docs/cli.md
Labels: Documentation

#2990 Multiple fixes for repository http authentication
  poetry/factory.py
  poetry/installation/authenticator.py
  poetry/repositories/auth.py
  poetry/repositories/legacy_repository.py
  tests/installation/test_authenticator.py
  tests/repositories/test_auth.py
  tests/repositories/test_legacy_repository.py
  tests/utils/test_exporter.py
Labels: Bug

#2448 poetry init uses existing pyproject.toml if possible
  poetry/console/commands/init.py
  poetry/layouts/layout.py
  tests/console/commands/test_init.py
Labels: Feature

#2984 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#3000 env: enable usersite for system environments
  poetry/masonry/builders/editable.py
  poetry/utils/env.py
  tests/utils/test_env.py
Labels: Bug
