Repository python-poetry/poetry, pull requests merged in 2020-06, with the labels that each got.

#2407 Small improvements to docs for version command
  docs/docs/cli.md
Labels: Documentation

#1140 fix: Gracefully handle read-only sdists
  poetry/utils/helpers.py
Labels: Bug

#2443 Update shell completion docs for prezto
  README.md
  docs/docs/index.md
Labels: Documentation

#2392 Document expanded table syntax for dependencies
  docs/docs/dependency-specification.md
Labels: Documentation

#2398 Fix resolution of path, url and VCS dependencies
  poetry/installation/pip_installer.py
  poetry/mixology/version_solver.py
  poetry/packages/directory_dependency.py
  poetry/packages/file_dependency.py
  poetry/packages/package.py
  poetry/packages/url_dependency.py
  poetry/packages/vcs_dependency.py
  poetry/puzzle/provider.py
  tests/fixtures/directory/project_with_transitive_directory_dependencies/pyproject.toml
  tests/fixtures/directory/project_with_transitive_file_dependencies/inner-directory-project/pyproject.toml
  tests/fixtures/directory/project_with_transitive_file_dependencies/pyproject.toml
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-file-dependency-transitive.test
  tests/installation/test_installer.py
  tests/puzzle/test_provider.py
  tests/puzzle/test_solver.py
Labels: Dependency resolution, Installation

#2429 Update the self update command to handle future versions
  poetry/console/commands/self/update.py
  tests/console/commands/self/__init__.py
  tests/console/commands/self/fixtures/poetry-1.0.5-darwin.sha256sum
  tests/console/commands/self/fixtures/poetry-1.0.5-darwin.tar.gz
  tests/console/commands/self/test_update.py
Labels: Improvement, Installer

#2484 Fix legacy repositories information not being set on packages
  poetry/repositories/legacy_repository.py
  tests/repositories/test_legacy_repository.py
Labels: Bug

#2497 Release 1.0.6
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2499 Fix a TypeError when trying to execute `setup.py` files
  poetry/puzzle/provider.py
Labels: Bug

#2500 Release 1.0.7
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2505 Fix root package and directory dependency editable installation
  poetry/installation/pip_installer.py
  poetry/masonry/builders/editable.py
  tests/masonry/builders/test_editable.py
Labels: Bug

#2506 Release 1.0.8
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2525 Fix legacy repositories packages being continuously updated
  poetry/puzzle/solver.py
  tests/puzzle/test_solver.py
Labels: Bug, Installation

#2526 Fix handling of dependency markers with python precision >= 3
  poetry/packages/dependency.py
  poetry/version/markers.py
  tests/packages/test_dependency.py
  tests/packages/test_main.py
Labels: Bug, Installation, Packaging

#2532 Release 1.0.9
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2426 Backport changes to the `get-poetry.py` file to master
  README.md
  get-poetry.py
Labels: Installer

#2544 Revert "get-poetry.py fallback to standard executables (#1878) (#2426)"
  .github/workflows/main.yml
  README.md
  get-poetry.py
Labels: Installer

#2547 Make get-poetry.py fallback to standard executables
  docs/docs/index.md
  get-poetry.py
Labels: Installer

#2482 Fix handling of markers in old lock files
  poetry/installation/installer.py
  tests/installation/test_installer.py
Labels: Bug, Installation

#2537 Broken Link: Index -> Managing Environments
  docs/docs/index.md
Labels: Documentation

#2396 Add solutions for common errors
  poetry.lock
  poetry/console/config/application_config.py
  poetry/mixology/failure.py
  poetry/mixology/solutions/__init__.py
  poetry/mixology/solutions/providers/__init__.py
  poetry/mixology/solutions/providers/python_requirement_solution_provider.py
  poetry/mixology/solutions/solutions/__init__.py
  poetry/mixology/solutions/solutions/python_requirement_solution.py
  poetry/mixology/version_solver.py
  pyproject.toml
  tests/mixology/solutions/__init__.py
  tests/mixology/solutions/providers/__init__.py
  tests/mixology/solutions/providers/test_python_requirement_solution_provider.py
  tests/mixology/solutions/solutions/__init__.py
  tests/mixology/solutions/solutions/test_python_requirement_solution.py
  tests/mixology/version_solver/test_python_constraint.py
Labels: CLI, UX

#1634 Provide hints when an invalid license id is input
  poetry/spdx/__init__.py
  tests/spdx/test_main.py
Labels: Error Handling

#2561 Python version option (`--python`) for `init` script.
  docs/docs/cli.md
  poetry/console/commands/init.py
  tests/console/commands/test_init.py
Labels: Feature

#1935 Add error handling for malfoemed author
  poetry/packages/package.py
  tests/packages/test_package.py
Labels: Error Handling

#2596 Release 1.1.0a2
  CHANGELOG.md
  Makefile
  make-nix-release.sh
  poetry.lock
  poetry/__version__.py
  pyproject.toml
Labels: Release
