Repository python-poetry/poetry, pull requests merged in 2020-01, with the labels that each got.

#1799 create valid PEP508 string for git dependencies with ssh (#1697)
  poetry/packages/vcs_dependency.py
  poetry/vcs/git.py
  tests/packages/test_vcs_dependency.py
Labels: Bug, Packaging

#1737 fix: removed hint for uninstall poetry, after installation.
  get-poetry.py
Labels: Documentation

#1592 Handle nested wildcards in package includes correctly. Fixes: #1379.
  poetry/masonry/builders/sdist.py
  poetry/masonry/utils/package_include.py
  tests/masonry/builders/fixtures/complete/my_package/sub_pkg3/foo.py
  tests/masonry/builders/test_complete.py
  tests/masonry/builders/test_sdist.py
  tests/masonry/utils/__init__.py
  tests/masonry/utils/fixtures/with_includes/__init__.py
  tests/masonry/utils/fixtures/with_includes/bar/baz.py
  tests/masonry/utils/fixtures/with_includes/extra_package/some_dir/foo.py
  tests/masonry/utils/fixtures/with_includes/extra_package/some_dir/quux.py
  tests/masonry/utils/fixtures/with_includes/not_a_python_pkg/baz.txt
  tests/masonry/utils/test_package_include.py
Labels: Bug

#1797 force recreation of venv if it is not sane (#286)
  poetry/utils/env.py
Labels: Bug, Virtualenvs

#1796 create PEP508 compliant dependency string for directory and file dependencies
  poetry/packages/directory_dependency.py
  poetry/packages/file_dependency.py
  tests/packages/test_directory_dependency.py
  tests/packages/test_file_dependency.py
Labels: Bug

#1829 Properly propagate dependency markers
  poetry/packages/dependency.py
  poetry/packages/utils/utils.py
  poetry/puzzle/provider.py
  poetry/puzzle/solver.py
  poetry/version/markers.py
  tests/installation/fixtures/with-duplicate-dependencies-update.test
  tests/installation/test_installer.py
  tests/puzzle/test_solver.py
  tests/version/test_markers.py
Labels: Bug, Dependency resolution

#1860 Release 1.0.1
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#1866 Release 1.0.2
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#1875 get_requires_for_build_wheel must return additional build requirements and not dependencies (#1689)
  poetry/masonry/api.py
  tests/masonry/test_api.py
Labels: Bug

#1910 Fix errors when using the --help option
  poetry/console/config/application_config.py
Labels: Bug, CLI

#1909 Fix how repository credentials are retrieved from env vars
  poetry/utils/password_manager.py
  tests/utils/test_password_manager.py
Labels: Bug, Configuration

#1966 Release 1.0.3
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release
