Repository python-poetry/poetry, pull requests merged in 2020-11, with the labels that each got.

#3313 Remove unused functions
  poetry/config/config.py
  poetry/console/commands/config.py
  poetry/console/commands/run.py
  poetry/console/commands/self/update.py
  poetry/mixology/version_solver.py
  poetry/puzzle/provider.py
  poetry/utils/setup_reader.py
Labels: Refactor

#3169 Use `.zshrc` instead of `.zprofile`
  get-poetry.py
Labels: hacktoberfest-accepted

#1594 Conda also has a dependency resolver in Python. Resolves: #477.
  README.md
Labels: Documentation
