Repository python-poetry/poetry, pull requests merged in 2020-10, with the labels that each got.

#3015 env/run: ensure all args are quoted as required
  poetry/utils/_compat.py
  tests/utils/test_env.py
Labels: Bug, Virtualenvs

#3009 Release 1.1.0
  CHANGELOG.md
  poetry/__version__.py
  poetry/layouts/layout.py
  pyproject.toml
Labels: Release

#3035 Fix resolution of packages with missing required extras
  poetry/puzzle/provider.py
  poetry/repositories/repository.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3036 Bugfix port: Fix resolution of packages with missing required extras
  poetry/puzzle/provider.py
  poetry/repositories/repository.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3024 exporter: handle dev extras correctly
  poetry/packages/locker.py
  poetry/utils/exporter.py
  tests/utils/test_exporter.py
Labels: Bug

#3037 Don't swallow ImportError in temporary_directory()
  get-poetry.py
Labels: Bug

#3038 exporter: handle dev extras correctly
  poetry/packages/locker.py
  poetry/utils/exporter.py
  tests/utils/test_exporter.py
Labels: Bug

#3034 lock: allow for no-update refresh of lock files
  poetry/console/commands/lock.py
  poetry/installation/installer.py
  tests/installation/fixtures/old-lock-refresh.test
  tests/installation/test_installer.py
Labels: Feature

#3058 install: skip unsupported binary distributions
  poetry/installation/chooser.py
Labels: Bug

#3056 build: ensure build uses project environment
  poetry/console/commands/build.py
Labels: Bug

#3076 init: handle pyproject exceptions for existing file
  poetry/console/commands/init.py
  tests/console/commands/test_init.py
Labels: Bug

#3051 lock: resolve dependencies on no-update
  poetry/installation/installer.py
  tests/console/commands/test_lock.py
  tests/fixtures/old_lock/poetry.lock
  tests/fixtures/old_lock/pyproject.toml
  tests/fixtures/old_lock/updated.lock
  tests/installation/fixtures/old-lock-refresh.test
  tests/installation/test_installer.py
Labels: Bug

#3047 publish: ensure config url is preferred
  poetry/factory.py
  tests/publishing/test_publisher.py
Labels: Bug

#3046 provider: ensure ony activated extras are used
  poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3081 Release 1.1.1
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#3099 executor: execute parallel unsafe ops serially
  poetry/installation/executor.py
Labels: Bug

#3100 export: fix handling of nested git dependencies
  poetry/utils/exporter.py
Labels: Bug

#3105 info: enhance local path poetry project support
  poetry/inspection/info.py
  tests/conftest.py
  tests/fixtures/project_with_nested_local/bar/pyproject.toml
  tests/fixtures/project_with_nested_local/foo/pyproject.toml
  tests/fixtures/project_with_nested_local/pyproject.toml
  tests/fixtures/project_with_nested_local/quix/pyproject.toml
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/installation/test_installer.py
  tests/installation/test_installer_old.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3108 Bump version to 1.1.2
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#3147 inspection: add each extra package as a dependency
  poetry/inspection/info.py
  tests/repositories/test_legacy_repository.py
  tests/repositories/test_pypi_repository.py
Labels: Bug

#3117 show: ignore dependency source when finding package
  poetry/console/commands/show.py
Labels: Bug

#3083 publish: raise an error on redirects
  poetry/publishing/uploader.py
  tests/publishing/test_uploader.py
Labels: hacktoberfest-accepted

#3204 Bump version to 1.1.3
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#3244 Run test lock no update on windows environments
  tests/console/commands/test_lock.py
Labels: Testing, hacktoberfest-accepted

#3233 Add command catch KeyboardInterrupt and restore original_content (2933, 318)
  poetry/console/commands/add.py
  tests/console/commands/test_add.py
Labels: Hacktoberfest, hacktoberfest-accepted

#3014 Add --trusted-host for non HTTPS repo (#1894)
  poetry/utils/exporter.py
  tests/utils/test_exporter.py
Labels: hacktoberfest-accepted

#3237 locker: handle cyclic dependencies during walk
  poetry/packages/locker.py
  tests/utils/test_exporter.py
Labels: Bug

#3264 Ensure vcs dependencies preserve editable flag
  poetry/packages/locker.py
  poetry/puzzle/provider.py
  tests/packages/test_locker.py
  tests/puzzle/test_provider.py
Labels: Bug

#3210 Handle non-editable packages with pth files
  poetry/repositories/installed_repository.py
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/standard-1.2.3.dist-info/METADATA
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/standard.pth
  tests/repositories/test_installed_repository.py
Labels: Bug

#3230 Do not reuse requests sessions
  poetry/installation/authenticator.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pypi_repository.py
Labels: Bug

#3251 pool: ensure sources are prioritised over PyPI
  poetry/factory.py
  tests/fixtures/with_non_default_source/pyproject.toml
  tests/test_factory.py
Labels: Bug, Repository

#3107 Improved support for system environment
  poetry/installation/pip_installer.py
  poetry/masonry/builders/editable.py
  poetry/utils/env.py
  poetry/utils/helpers.py
  tests/installation/test_pip_installer.py
  tests/masonry/builders/test_editable_builder.py
  tests/utils/test_env.py
  tests/utils/test_env_site.py
Labels: Bug

#3276 Bump version to 1.1.4
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#3232 Documentation: Add no interaction flag to website
  docs/docs/cli.md
Labels: Documentation, hacktoberfest-accepted

#3278 pip installer: fix incorrect method call
  poetry/installation/pip_installer.py
Labels: Bug

#3279 pip installer: fix incorrect method call
  poetry/installation/pip_installer.py
Labels: Bug
