Repository python-poetry/poetry, pull requests merged in 2020-04, with the labels that each got.

#2256 package: allow url dependencies to be optional
  poetry/packages/package.py
  tests/packages/test_package.py
Labels: Bug

#2265 [Bugfix] Moved access to first element to after the length check
  poetry/masonry/utils/package_include.py
  tests/masonry/utils/test_package_include.py
Labels: Error Handling

#2147 try to find shell via os.environ if detect_shell fail (#2115)
  poetry/utils/shell.py
Labels: Error Handling

#2279 doc: explain why `update` sometimes causes a no-op
  docs/docs/cli.md
Labels: Documentation

#2299 Add Triage label to new issues and clean the PR template.
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---documentation.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Documentation

#2297 FreeBSD Testing / Release Automation
  .cirrus.yml
  Makefile
  make-linux-release.sh
  make-nix-release.sh
Labels: Installer

#2277 Add --lock option to the `add` command
  docs/docs/cli.md
  poetry/console/commands/add.py
  tests/console/commands/test_add.py
Labels: Feature

#2162 Allow offline Poetry install with pre-downloaded release file
  get-poetry.py
Labels: Installer

#2121 remove 'm' and 'd' ABI tags for Python 3.8 wheels
  poetry/masonry/utils/tags.py
  poetry/utils/env.py
  tests/masonry/utils/test_tags.py
Labels: Bug
