Repository python-poetry/poetry, pull requests merged in 2020-02, with the labels that each got.

#2018 Fix non-compliant Git URL matching
  poetry/vcs/git.py
  tests/vcs/test_git.py
Labels: Bug

#2040 Update README.md "Updating Poetry"
  README.md
Labels: Documentation

#1519 init: change dev dependency prompt
  poetry/console/commands/init.py
Labels: CLI, Installation

#2041 fix (#2038): "Call" object has no attribute "id"
  poetry/utils/setup_reader.py
Labels: Bug

#1948 fix(git): get commit sha of git commit from annotated tags
  poetry/vcs/git.py
Labels: Bug

#1981 Fix vendor package as installed package (#1883)
  poetry/repositories/installed_repository.py
  tests/repositories/fixtures/installed/vendor/py3.7/attrs-19.3.0.dist-info/METADATA
  tests/repositories/test_installed_repository.py
Labels: Bug

#2096 fix(utils.env): import cli_run from virtualenv
  poetry/utils/env.py
Labels: Bug

#1762 list .venv when it exists
  poetry/utils/env.py
  tests/console/commands/env/test_list.py
Labels: Bug

#1626 fix: exclude subpackage from `setup.py` if `__init__.py` is excluded (#1009)
  poetry/masonry/builders/sdist.py
  tests/masonry/builders/fixtures/excluded_subpackage/README.rst
  tests/masonry/builders/fixtures/excluded_subpackage/example/__init__.py
  tests/masonry/builders/fixtures/excluded_subpackage/example/test/__init__.py
  tests/masonry/builders/fixtures/excluded_subpackage/example/test/excluded.py
  tests/masonry/builders/fixtures/excluded_subpackage/pyproject.toml
  tests/masonry/builders/test_sdist.py
Labels: Bug

#1947 get_vcs starts searching git folder from tmp dir instead of project (#1946)
  poetry/masonry/builders/builder.py
  poetry/vcs/__init__.py
Labels: Bug

#2006 Normalize author name unicode before matching
  poetry/packages/package.py
  tests/packages/test_package.py
Labels: Bug

#2099 Fix the url used for installation when fallbacking on PyPI
  poetry/repositories/pypi_repository.py
  poetry/repositories/remote_repository.py
  tests/repositories/test_pypi_repository.py
Labels: Bug, Installation

#2101 Release 1.0.4
  .github/workflows/release.yml
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2112 Release 1.0.5
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release
