Repository python-poetry/poetry, pull requests merged in 2020-03, with the labels that each got.

#1187 Add cache list command
  docs/docs/cli.md
  poetry/console/commands/cache/cache.py
  poetry/console/commands/cache/clear.py
  poetry/console/commands/cache/list.py
  poetry/locations.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pypi_repository.py
  tests/console/commands/test_cache.py
Labels: Feature

#1862 Document --no-root
  docs/docs/basic-usage.md
  poetry/console/commands/install.py
Labels: Documentation

#2233 Update the installer script to handle future releases
  get-poetry.py
Labels: Installer

#2199 Add --dry-run option for publish command
  docs/docs/cli.md
  poetry/console/commands/publish.py
  poetry/publishing/publisher.py
  poetry/publishing/uploader.py
  tests/console/commands/test_publish.py
  tests/publishing/test_publisher.py
Labels: Feature

#2235 Release 1.1.0a1
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2229 clarify wildcard dependency specification
  docs/docs/dependency-specification.md
Labels: Documentation

#2122 Rename secondary "tests" package in doc example
  docs/docs/pyproject.md
Labels: Documentation

#1830 Add fish shell tab completion for mac
  README.md
  docs/docs/index.md
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/cleo-0.7.6.dist-info/METADATA
Labels: Documentation

#1653 fix: Add information about valid export formats to help page
  poetry/console/commands/export.py
Labels: Documentation
