Repository python-poetry/poetry, pull requests merged in 2020-07, with the labels that each got.

#2622 Fix dependency overrides for packages with multiple duplicate dependencies
  poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: Dependency resolution

#2625 Use proper main python constraint when resolving for installation
  poetry/puzzle/provider.py
  poetry/puzzle/solver.py
  poetry/utils/env.py
  tests/mixology/version_solver/conftest.py
  tests/mixology/version_solver/test_python_constraint.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution, Installation

#2648 Release 1.1.0a3
  .github/workflows/release.yml
  CHANGELOG.md
  make-nix-release.sh
  poetry.lock
  poetry/__version__.py
  pyproject.toml
  sonnet
Labels: Release

#2656 Ensure tasks are cancelled when executor is shut down
  poetry/installation/executor.py
Labels: Installation

#2664 editable builder: handle package includes correctly
  poetry/masonry/builders/editable.py
  tests/masonry/builders/test_editable_builder.py
Labels: Bug

#2695 Add lock versioning support
  poetry/console/config/application_config.py
  poetry/packages/locker.py
  tests/installation/fixtures/extras-with-dependencies.test
  tests/installation/fixtures/extras.test
  tests/installation/fixtures/install-no-dev.test
  tests/installation/fixtures/no-dependencies.test
  tests/installation/fixtures/remove.test
  tests/installation/fixtures/update-with-lock.test
  tests/installation/fixtures/update-with-locked-extras.test
  tests/installation/fixtures/with-category-change.test
  tests/installation/fixtures/with-conditional-dependency.test
  tests/installation/fixtures/with-dependencies-extras.test
  tests/installation/fixtures/with-dependencies.test
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/installation/fixtures/with-directory-dependency-setuptools.test
  tests/installation/fixtures/with-duplicate-dependencies-update.test
  tests/installation/fixtures/with-duplicate-dependencies.test
  tests/installation/fixtures/with-file-dependency-transitive.test
  tests/installation/fixtures/with-file-dependency.test
  tests/installation/fixtures/with-multiple-updates.test
  tests/installation/fixtures/with-optional-dependencies.test
  tests/installation/fixtures/with-platform-dependencies.test
  tests/installation/fixtures/with-prereleases.test
  tests/installation/fixtures/with-pypi-repository.test
  tests/installation/fixtures/with-python-versions.test
  tests/installation/fixtures/with-sub-dependencies.test
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/fixtures/with-wheel-dependency-no-requires-dist.test
  tests/packages/test_locker.py
Labels: Feature, UX

#2696 Release 1.0.10
  .github/workflows/release.yml
  CHANGELOG.md
  Makefile
  make-linux-release.sh
  poetry.lock
  poetry/__version__.py
  pyproject.toml
  sonnet
Labels: Release

#2709 Fix errors on Python 2.7 when a file could not be downloaded
  poetry/installation/executor.py
  tests/installation/test_executor.py
Labels: Bug

#2710 Fix the lock content hash not being updated with the add/remove commands
  poetry/console/commands/installer_command.py
  poetry/console/commands/remove.py
  poetry/installation/installer.py
  tests/console/commands/test_add.py
  tests/console/conftest.py
Labels: Bug

#2712 Fix incorrect resolution errors for dependencies with looser python constraints
  poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#2715 Display logging messages from poetry-core when building
  .github/workflows/main.yml
  poetry.lock
  poetry/console/commands/build.py
  poetry/console/config/application_config.py
  poetry/console/logging/formatters/__init__.py
  poetry/console/logging/formatters/builder_formatter.py
  poetry/console/logging/io_handler.py
  pyproject.toml
  tests/masonry/builders/test_editable_builder.py
  tests/test_factory.py
  tests/utils/test_env.py
Labels: CLI, Packaging

#2716 Release 1.1.0b1
  CHANGELOG.md
  poetry.lock
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2717 Fix compatibility check for lock files
  poetry/packages/locker.py
  tests/packages/test_locker.py
Labels: Bug, Installation

#2718 Add support for build scripts without `setup.py` generation in the editable builder
  poetry/masonry/builders/editable.py
  tests/fixtures/extended_project_without_setup/README.rst
  tests/fixtures/extended_project_without_setup/build.py
  tests/fixtures/extended_project_without_setup/extended_project/__init__.py
  tests/fixtures/extended_project_without_setup/pyproject.toml
  tests/masonry/builders/test_editable_builder.py
Labels: Feature, Installation

#2719 Release 1.1.0b2
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2722 Improve detection of installed packages in an environment
  poetry/repositories/installed_repository.py
  poetry/utils/env.py
  tests/fixtures/complete.toml
  tests/installation/test_installer.py
  tests/installation/test_installer_old.py
  tests/repositories/fixtures/installed/lib64/python3.7/site-packages/bender-2.0.5.dist-info/METADATA
  tests/repositories/fixtures/installed/lib64/python3.7/site-packages/bender.pth
  tests/repositories/fixtures/installed/lib64/python3.7/site-packages/lib64-2.3.4.dist-info/METADATA
  tests/repositories/fixtures/installed/src/bender/bender.egg-info/PKG-INFO
  tests/repositories/test_installed_repository.py
Labels: Bug
