Repository python-poetry/poetry, pull requests merged in 2020-08, with the labels that each got.

#2637 Fix doc/pyproject.md
  docs/docs/pyproject.md
Labels: Documentation

#2459 Display better messages on legacy repo HTTP errors
  poetry/repositories/legacy_repository.py
  tests/repositories/test_legacy_repository.py
Labels: Error Handling

#2417 added venv quickstart info
  docs/docs/basic-usage.md
Labels: Documentation

#2641 Add note for setting up poetry in a pre-existing project.
  docs/docs/basic-usage.md
Labels: Documentation

#2821 Handle (*) constraint for pre-release only packages
  poetry/repositories/legacy_repository.py
  poetry/repositories/pypi_repository.py
  poetry/repositories/repository.py
  tests/repositories/fixtures/legacy/black.html
  tests/repositories/fixtures/pypi.org/dists/black-19.10b0-py36-none-any.whl
  tests/repositories/fixtures/pypi.org/json/black.json
  tests/repositories/test_legacy_repository.py
  tests/repositories/test_pypi_repository.py
Labels: Bug

#2810 info: enable PEP 517 fallback builds by default
  poetry/inspection/info.py
  poetry/puzzle/provider.py
  tests/conftest.py
  tests/inspection/test_info.py
Labels: Bug

#2787 Handle circular dependencies when getting extras
  poetry/utils/extras.py
  tests/utils/test_extras.py
Labels: Bug
