Repository python-poetry/poetry, pull requests merged in 2021-11, with the labels that each got.

#4362 Update packaging requirement to support 21.0
  pyproject.toml
Labels: Dependency

#4574 Rename whitelist_externals in FAQ
  docs/faq.md
  pyproject.toml
  tox.ini
Labels: Documentation, Testing

#4636 Updates the documentation to state that it supports Python 3.6+.
  README.md
  docs/_index.md
  docs/configuration.md
  docs/managing-environments.md
Labels: Documentation, hacktoberfest-accepted

#4736 Clean up old scripts/build tools
  Makefile
  make-nix-release.sh
  poetry/utils/env.py
  sonnet
Labels: Automation, Cleanup

#4099 installer: use venv and improve error handling
  .github/workflows/installer.yml
  install-poetry.py
Labels: Installer

#4735 Clean up .cirrus.yml
  .cirrus.yml
Labels: Automation

#4737 Update basic-usage.md with current pyproject.toml structure
  docs/basic-usage.md
Labels: Documentation

#4748 Revert "Update packaging requirement to support 21.0"
  pyproject.toml
Labels: Upstream Issue, Dependency

#4733 Separate the package and the platform constraints in poetry export
  poetry/utils/exporter.py
  tests/utils/test_exporter.py
Labels: Bug, PEP

#4753 fix: Fix test failures after merge of #4686
  tests/utils/test_exporter.py
Labels: Testing

#4754 docs: add more badges to README
  README.md
Labels: Documentation

#3257 Updates in Basic Usage Documentation for further specification on project and module names
  docs/basic-usage.md
Labels: Documentation

#3212 Remove all env
  docs/managing-environments.md
  poetry/console/commands/env/remove.py
  tests/console/commands/env/test_remove.py
Labels: hacktoberfest-accepted

#1181 Enhancement: add "extras" example to scripts docs
  docs/pyproject.md
Labels: Documentation

#4836 Release 1.1.12
  CHANGELOG.md
  poetry/__version__.py
  pyproject.toml
Labels: Release

#2511 Feature: Add poetry as pre-commit hook
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  docs/cli.md
  docs/pre-commit-hooks.md
Labels: Feature
