Repository python-poetry/poetry, pull requests merged in 2021-04, with the labels that each got.

#3861 Used pyupgrade to remove compatibility code
  poetry/config/config.py
  poetry/config/config_source.py
  poetry/console/application.py
  poetry/inspection/info.py
  poetry/installation/authenticator.py
  poetry/installation/chef.py
  poetry/installation/chooser.py
  poetry/installation/executor.py
  poetry/installation/installer.py
  poetry/installation/pip_installer.py
  poetry/json/__init__.py
  poetry/layouts/layout.py
  poetry/layouts/src.py
  poetry/layouts/standard.py
  poetry/mixology/assignment.py
  poetry/mixology/failure.py
  poetry/mixology/incompatibility.py
  poetry/mixology/partial_solution.py
  poetry/mixology/term.py
  poetry/mixology/version_solver.py
  poetry/packages/dependency_package.py
  poetry/packages/locker.py
  poetry/packages/package_collection.py
  poetry/plugins/base_plugin.py
  poetry/plugins/plugin_manager.py
  poetry/publishing/publisher.py
  poetry/publishing/uploader.py
  poetry/puzzle/exceptions.py
  poetry/puzzle/provider.py
  poetry/puzzle/solver.py
  poetry/repositories/base_repository.py
  poetry/repositories/legacy_repository.py
  poetry/repositories/pool.py
  poetry/repositories/pypi_repository.py
  poetry/repositories/remote_repository.py
  poetry/repositories/repository.py
  poetry/utils/_compat.py
  poetry/utils/env.py
  poetry/utils/exporter.py
  poetry/utils/helpers.py
  poetry/utils/password_manager.py
  poetry/utils/setup_reader.py
  poetry/utils/shell.py
  poetry/version/version_selector.py
Labels: Refactor

#3903 Fix reverting the pyproject.toml content in the remove command
  poetry/console/commands/remove.py
  tests/console/commands/test_remove.py
Labels: Bug

#3937 Update CLI docs to include information about poetry lock --no-update
  docs/docs/cli.md
Labels: Documentation

#3944 Fix incorrect package being selected with transitive markers
  poetry/mixology/version_solver.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3945 [1.1] Fix incorrect package being selected with transitive markers
  poetry/mixology/version_solver.py
  tests/puzzle/test_solver.py
Labels: Bug, Dependency resolution

#3947 [1.1] Fix locked VCS dependencies always being updated
  poetry/installation/executor.py
  poetry/installation/installer.py
  poetry/installation/pip_installer.py
  tests/installation/test_installer.py
Labels: Bug, Installation

#3905 Release 1.1.6
  CHANGELOG.md
  poetry.lock
  poetry/__version__.py
  pyproject.toml
Labels: Release
