Repository python-poetry/poetry, pull requests merged in 2021-03, with the labels that each got.

#3750 Release 1.1.5
  .cirrus.yml
  .github/workflows/release.yml
  CHANGELOG.md
  Makefile
  poetry.lock
  poetry/__version__.py
  pyproject.toml
Labels: Release

#3156 Doc: Update for the "extras" section in pyproject.toml file
  docs/docs/pyproject.md
Labels: hacktoberfest-accepted

#1954 #453 Add command to check poetry.lock freshness
  docs/docs/cli.md
  docs/docs/pyproject.md
  poetry/console/commands/lock.py
  tests/console/commands/test_lock.py
  tests/fixtures/outdated_lock/poetry.lock
  tests/fixtures/outdated_lock/pyproject.toml
  tests/fixtures/up_to_date_lock/poetry.lock
  tests/fixtures/up_to_date_lock/pyproject.toml
Labels: Feature

#3192 docs/configuration: fix note markdown
  docs/docs/configuration.md
Labels: Documentation

#2268 Add documentation on inline tables in include. Resolves: Core #8.
  docs/docs/pyproject.md
Labels: Documentation, need/core-next
