Repository python-poetry/poetry, pull requests merged in 2022-10, with the labels that each got.

#6672 docs: fix reference to invalid option --require
  docs/cli.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6683 docs(basic-usage): add PowerShell one-liner
  docs/basic-usage.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6679 provider: do not merge dependencies from different sources
  src/poetry/puzzle/provider.py
  tests/puzzle/test_provider.py
  tests/puzzle/test_solver.py
Labels: area/solver, kind/enhancement, impact/changelog

#6690 ci: simplify Cirrus testing
  .cirrus.yml
Labels: area/ci, impact/backport, backport/1.2

#6695 ci(cirrus): increase core count thanks to increased concurrency limits for OSS
  .cirrus.yml
Labels: area/ci, impact/backport, backport/1.2

#6699 ci: remove obsolete certificates installation on MacOS
  .github/workflows/main.yml
Labels: area/ci

#6541 canonicalized extra names
  poetry.lock
  pyproject.toml
  src/poetry/console/commands/install.py
  src/poetry/installation/installer.py
  src/poetry/packages/locker.py
  src/poetry/puzzle/provider.py
  src/poetry/utils/extras.py
  src/poetry/utils/helpers.py
  tests/console/commands/test_install.py
  tests/installation/fixtures/with-dependencies-nested-extras.test
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/puzzle/test_provider.py
  tests/repositories/test_pypi_repository.py
  tests/test_factory.py
  tests/utils/test_helpers.py
Labels: area/installer, status/waiting-on-core, impact/backport, impact/changelog, backport/1.2

#6561 fix: fix failing tests due to updated list of available pythons
  poetry.lock
  pyproject.toml
  tests/masonry/builders/test_editable_builder.py
  tests/test_factory.py
Labels: area/testing, impact/backport, backport/1.2

#6621 normalized sdist names
  src/poetry/publishing/uploader.py
  tests/helpers.py
Labels: kind/bug, area/build-system, area/publishing, impact/backport, impact/changelog, backport/1.2

#6724 Pip no input
  src/poetry/utils/pip.py
Labels: area/installer, kind/enhancement, impact/changelog

#6730 fix: turn debug message about invalid constraint into warning
  src/poetry/inspection/info.py
Labels: area/error-handling, impact/backport, impact/changelog, backport/1.2

#6734 locker: less verbose output for `package.files` in lock file 2.0
  src/poetry/packages/locker.py
  tests/packages/test_locker.py
Labels: kind/refactor, area/deps

#6560 adds fallback behavior for non-ms shells
  src/poetry/utils/shell.py
Labels: kind/bug, impact/backport, area/windows, status/2-code-review, impact/changelog, backport/1.2, area/shell

#6739 docs(plugins): change the example's minimum poetry version to 1.2
  docs/plugins.md
Labels: impact/backport, backport/1.2

#6753 feat(locker): `poetry lock` works if an invalid/incompatible lock file exists
  .pre-commit-config.yaml
  src/poetry/installation/installer.py
  src/poetry/packages/locker.py
  tests/console/commands/test_lock.py
  tests/fixtures/incompatible_lock/poetry.lock
  tests/fixtures/incompatible_lock/pyproject.toml
  tests/fixtures/invalid_lock/poetry.lock
  tests/fixtures/invalid_lock/pyproject.toml
Labels: area/error-handling, area/ux, impact/backport, backport/1.2, area/deps

#6731 release: bump version to 1.2.2
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: kind/release

#6760 chore: add missing CHANGELOG entry for 1.1.15
  CHANGELOG.md
Labels: impact/backport, area/project, backport/1.2

#6770 Add changelog URL to package metadata
  pyproject.toml
Labels: area/distribution

#6779 fix: Add post init check for `FileCache` hash type.
  src/poetry/utils/cache.py
  tests/utils/test_cache.py
Labels: kind/enhancement, area/sources

#6780 ci: upgrade `pip` for 3.11 on all OSes
  .github/workflows/main.yml
Labels: area/ci

#6793 docs (intro): Add missing dash to command enabling completion in bash
  docs/_index.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6842 fix(docs): broken link in dependency-specification
  docs/dependency-specification.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6920 tests: add test for `poetry show` with multiple constraints dependencies
  tests/console/commands/test_show.py
Labels: area/testing
