Repository python-poetry/poetry, pull requests merged in 2022-05, with the labels that each got.

#5565 doc: improve repository documentation
  docs/repositories.md
Labels: Documentation

#5576 docs: remove ambiguity about pep440 and semver
  docs/cli.md
  docs/faq.md
  docs/libraries.md
  docs/pyproject.md
Labels: Documentation

#5578 docs: add information on git and http-basic auth
  docs/dependency-specification.md
Labels: Documentation

#5600 install: add --no-binary option
  docs/cli.md
  src/poetry/console/commands/install.py
  src/poetry/installation/chooser.py
  src/poetry/installation/executor.py
  src/poetry/installation/installer.py
  tests/console/commands/test_install.py
  tests/installation/test_chooser.py
Labels: CLI, Installation, Documentation

#5609 config: introduce `installer.no-binary`
  docs/cli.md
  docs/configuration.md
  src/poetry/config/config.py
  src/poetry/console/commands/config.py
  src/poetry/console/commands/install.py
  src/poetry/installation/chooser.py
  src/poetry/installation/executor.py
  src/poetry/installation/installer.py
  tests/console/commands/test_config.py
  tests/console/commands/test_install.py
  tests/installation/test_chooser.py
Labels: Installation, Configuration, Documentation

#5603 Add --dry-run option to version command
  docs/cli.md
  src/poetry/console/commands/version.py
  tests/console/commands/test_version.py
Labels: CLI, Documentation

#5618 Update Windows install instructions to target the py launcher
  docs/_index.md
Labels: Documentation

#5629 docs: add `--local` option in `config`
  docs/cli.md
Labels: Documentation

#5585 Add example for each section of `pyproject.toml`
  docs/pyproject.md
Labels: Documentation

#3390 Make test_installer.py test suite pass when run from any directory
  tests/installation/test_installer.py
Labels: Testing

#4606 Allow for empty choice while selecting dependencies
  src/poetry/console/commands/init.py
  tests/console/commands/test_init.py
Labels: CLI

#5642 Add name field reference to PEP 508
  docs/pyproject.md
Labels: Documentation

#3978 [Docs / Basic Usage] Use PowerShell on Windows
  docs/basic-usage.md
Labels: Documentation

#5653 clarify documentation for `--why` command
  docs/cli.md
  src/poetry/console/commands/show.py
Labels: Documentation

#5666 Fix PyPI capitalisation
  docs/pyproject.md
Labels: Documentation

#5492 [document] Mention poetry.toml
  docs/configuration.md
Labels: Documentation

#5606 Added virtualenvs.prompt option to config
  docs/configuration.md
  src/poetry/config/config.py
  src/poetry/console/commands/config.py
  src/poetry/utils/env.py
  tests/console/commands/env/test_use.py
  tests/console/commands/test_config.py
  tests/utils/test_env.py
Labels: Documentation

#5661 Add docs for multiple maintainers example
  docs/pyproject.md
Labels: Documentation

#5357 Allow any file extension for README file
  docs/cli.md
  src/poetry/layouts/layout.py
  tests/console/commands/test_new.py
Labels: Documentation, Consensus Needed

#5719 config: allow bool values for repo cert
  docs/configuration.md
  docs/repositories.md
  src/poetry/console/commands/config.py
  src/poetry/installation/pip_installer.py
  src/poetry/publishing/publisher.py
  src/poetry/publishing/uploader.py
  src/poetry/repositories/http.py
  src/poetry/utils/authenticator.py
  src/poetry/utils/helpers.py
  tests/console/commands/test_config.py
  tests/installation/test_pip_installer.py
  tests/publishing/test_publisher.py
  tests/utils/test_authenticator.py
  tests/utils/test_helpers.py
Labels: Configuration, Documentation, Repository

#5301 support for POETRY_CONFIG_DIR, POETRY_DATA_DIR and POETRY_CACHE_DIR environment variables
  docs/configuration.md
Labels: Documentation
