Repository python-poetry/poetry, pull requests merged in 2022-09, with the labels that each got.

#6318 docs: fix example for --with option combined with --without
  docs/managing-dependencies.md
Labels: Documentation

#6336 No unwanted update of packages from legacy source
  src/poetry/puzzle/provider.py
  tests/mixology/version_solver/test_with_lock.py
Labels: area/resolver, impact/backport, impact/changelog

#6345 docs: added ci recommendations
  docs/_index.md
Labels: area/docs, impact/docs

#6373 docs(ci): turn on syntax highlighting and tweak instructions
  docs/_index.md
Labels: area/docs, impact/docs, backport/1.2

#6376 fix virtualenv constraint
  poetry.lock
  pyproject.toml
Labels: impact/backport, backport/1.2, area/deps

#6383 tests: fix constraint
  tests/console/commands/test_show.py
Labels: impact/backport, backport/1.2

#6394 chore(dependabot): setup weekly schedule for `github-actions`
  .github/dependabot.yml
Labels: area/ci

#6402 fix virtualenv constraint (PEP 440 compliant)
  poetry.lock
  pyproject.toml
Labels: impact/backport, backport/1.2, area/deps

#6389 locker: do not assign unrelated filenames/hashes to direct origin dependencies
  src/poetry/packages/locker.py
  tests/packages/test_locker.py
Labels: area/installer, impact/backport, impact/changelog, backport/1.2

#6131 Do not fetch VCS deps when reference didn't change
  src/poetry/puzzle/provider.py
  tests/puzzle/test_solver.py
Labels: area/resolver, impact/changelog

#5767 fix: only consider package links for sdist and bdist_wheels
  src/poetry/repositories/pypi_repository.py
  tests/repositories/fixtures/pypi.org/json/hbmqtt.json
  tests/repositories/test_pypi_repository.py
Labels: impact/backport, impact/changelog, backport/1.2

#5738 Refactor `show` command a bit
  src/poetry/console/commands/show.py
Labels: area/cli, kind/refactor

#6442 fix: performance regression when parsing links from legacy repositories
  poetry.lock
  pyproject.toml
  src/poetry/repositories/link_sources/base.py
  src/poetry/repositories/link_sources/html.py
  src/poetry/utils/_compat.py
  tests/repositories/link_sources/test_base.py
  tests/repositories/link_sources/test_html.py
  tests/repositories/test_legacy_repository.py
Labels: area/resolver, impact/backport, impact/changelog, backport/1.2

#6460 docs: improved description of `virtualenvs.create` option
  docs/configuration.md
Labels: impact/docs

#6478 build(deps): refresh lock file
  poetry.lock
Labels: area/deps

#6479 respect --no-cache at poetry install
  src/poetry/console/application.py
  src/poetry/factory.py
  src/poetry/installation/executor.py
  src/poetry/installation/installer.py
  src/poetry/poetry.py
  tests/console/test_application.py
Labels: area/cli, impact/backport, impact/changelog, backport/1.2

#6475 Add missing deprecation warning for `--dev`
  docs/cli.md
  src/poetry/console/commands/add.py
  src/poetry/console/commands/remove.py
Labels: area/cli, impact/backport, impact/docs, backport/1.2

#6497 docs: added note about `pre-commit autoupdate`
  docs/pre-commit-hooks.md
Labels: impact/docs

#6509 fix: poetry-core>=1.1.0 is needed as build-system requirement
  pyproject.toml
Labels: impact/backport, backport/1.2

#6186 Fix a race condition in simultaneous poetry installations updating the cache
  src/poetry/installation/executor.py
  src/poetry/utils/helpers.py
Labels: area/installer, kind/refactor, impact/changelog

#6512 fix: wrong nested table level when overwriting pyproject
  src/poetry/console/commands/self/self_command.py
Labels: impact/backport, backport/1.2

#6537 fix(cache clear): normalize package name
  src/poetry/console/commands/cache/clear.py
  tests/console/commands/cache/test_clear.py
Labels: impact/backport, backport/1.2

#6504 release: bump version to 1.2.1
  CHANGELOG.md
  poetry.lock
  pyproject.toml
Labels: kind/release

#6477 solver: make results of `poetry update` more deterministic and similar to results of `poetry lock`
  src/poetry/mixology/version_solver.py
  tests/puzzle/test_solver.py
Labels: area/resolver, kind/enhancement, impact/changelog

#6476 don't use normalize_version()
  src/poetry/publishing/uploader.py
  tests/helpers.py
Labels: kind/refactor, status/4-merge, impact/changelog, area/uploader

#6471 Use filelock to lock the file cache
  poetry.lock
  pyproject.toml
  src/poetry/utils/authenticator.py
Labels: area/installer, kind/refactor, status/4-merge, impact/changelog

#6505 keyring and virtualenv are not using calver
  poetry.lock
  pyproject.toml
Labels: kind/enhancement, status/4-merge, area/deps

#6081 Avoid the deprecated JSON API
  src/poetry/repositories/link_sources/json.py
  src/poetry/repositories/pypi_repository.py
  src/poetry/utils/authenticator.py
  tests/installation/test_executor.py
  tests/repositories/fixtures/pypi.org/json/attrs.json
  tests/repositories/fixtures/pypi.org/json/black.json
  tests/repositories/fixtures/pypi.org/json/black/19.10b0.json
  tests/repositories/fixtures/pypi.org/json/cachecontrol.json
  tests/repositories/fixtures/pypi.org/json/clikit.json
  tests/repositories/fixtures/pypi.org/json/clikit/0.2.4.json
  tests/repositories/fixtures/pypi.org/json/colorama.json
  tests/repositories/fixtures/pypi.org/json/funcsigs.json
  tests/repositories/fixtures/pypi.org/json/hbmqtt.json
  tests/repositories/fixtures/pypi.org/json/hbmqtt/0.9.6.json
  tests/repositories/fixtures/pypi.org/json/isort.json
  tests/repositories/fixtures/pypi.org/json/isort/4.3.4.json
  tests/repositories/fixtures/pypi.org/json/jupyter.json
  tests/repositories/fixtures/pypi.org/json/jupyter/1.0.0.json
  tests/repositories/fixtures/pypi.org/json/lockfile.json
  tests/repositories/fixtures/pypi.org/json/more-itertools.json
  tests/repositories/fixtures/pypi.org/json/pluggy.json
  tests/repositories/fixtures/pypi.org/json/poetry.json
  tests/repositories/fixtures/pypi.org/json/py.json
  tests/repositories/fixtures/pypi.org/json/pygame-music-grid.json
  tests/repositories/fixtures/pypi.org/json/pylev.json
  tests/repositories/fixtures/pypi.org/json/pylev/1.3.0.json
  tests/repositories/fixtures/pypi.org/json/pytest.json
  tests/repositories/fixtures/pypi.org/json/pytest/3.5.1.json
  tests/repositories/fixtures/pypi.org/json/pyyaml.json
  tests/repositories/fixtures/pypi.org/json/pyyaml/3.13.0.json
  tests/repositories/fixtures/pypi.org/json/requests.json
  tests/repositories/fixtures/pypi.org/json/setuptools.json
  tests/repositories/fixtures/pypi.org/json/setuptools/39.2.0.json
  tests/repositories/fixtures/pypi.org/json/six.json
  tests/repositories/fixtures/pypi.org/json/sqlalchemy.json
  tests/repositories/fixtures/pypi.org/json/sqlalchemy/1.2.12.json
  tests/repositories/fixtures/pypi.org/json/toga.json
  tests/repositories/fixtures/pypi.org/json/tomlkit.json
  tests/repositories/fixtures/pypi.org/json/tomlkit/0.5.3.json
  tests/repositories/fixtures/pypi.org/json/trackpy.json
  tests/repositories/fixtures/pypi.org/json/trackpy/0.4.1.json
  tests/repositories/fixtures/pypi.org/json/twisted.json
  tests/repositories/fixtures/pypi.org/json/twisted/18.9.0.json
  tests/repositories/test_pypi_repository.py
Labels: kind/refactor, impact/backport, impact/changelog, backport/1.2, area/sources

#6195 Update env remove logic
  src/poetry/utils/env.py
  tests/console/commands/env/conftest.py
  tests/utils/conftest.py
  tests/utils/test_env.py
Labels: area/venv, kind/enhancement, impact/changelog

#2773 adds @generated to header of lockfile
  src/poetry/packages/locker.py
  tests/packages/test_locker.py
Labels: kind/feature, impact/changelog

#2881 Check project against valid and deprecated trove classifiers.
  poetry.lock
  pyproject.toml
  src/poetry/console/commands/check.py
  tests/console/commands/test_check.py
  tests/fixtures/invalid_pyproject/pyproject.toml
Labels: kind/feature, area/pyproject, impact/changelog

#5605 Update repositories.md
  docs/repositories.md
Labels: area/docs

#4417 Adds File existence check to Uploader
  src/poetry/publishing/uploader.py
  tests/publishing/test_uploader.py
Labels: kind/enhancement, impact/changelog, area/uploader

#6352 test(console/commands/init): package include
  tests/console/commands/test_init.py
Labels: area/testing, status/2-code-review

#6547 Prefer wheels over source distribution
  src/poetry/repositories/http.py
Labels: area/installer, kind/enhancement, impact/changelog

#6576 chore(ci): setup certificates for 3.11 on macOS
  .github/workflows/main.yml
Labels: area/ci

#6586 chore(ci): upgrade `pip` for 3.11 on macOS
  .github/workflows/main.yml
Labels: area/ci

#6588 docs: fix minor typos in README (and demo non-semver constraint)
  README.md
Labels: area/docs, impact/backport, backport/1.2

#6604 Fix for inconsistent docs for multiple constraint dependencies (GH6603)
  docs/dependency-specification.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6393 feat: lock file format 2.0 (was: store package files on the package in lockfile)
  src/poetry/packages/locker.py
  tests/console/commands/self/test_remove_plugins.py
  tests/console/commands/test_lock.py
  tests/console/commands/test_show.py
  tests/fixtures/old_lock/updated.lock
  tests/fixtures/outdated_lock/poetry.lock
  tests/fixtures/up_to_date_lock/poetry.lock
  tests/installation/fixtures/extras-with-dependencies.test
  tests/installation/fixtures/extras.test
  tests/installation/fixtures/install-no-dev.test
  tests/installation/fixtures/no-dependencies.test
  tests/installation/fixtures/remove.test
  tests/installation/fixtures/update-with-lock.test
  tests/installation/fixtures/update-with-locked-extras.test
  tests/installation/fixtures/with-category-change.test
  tests/installation/fixtures/with-conditional-dependency.test
  tests/installation/fixtures/with-dependencies-extras.test
  tests/installation/fixtures/with-dependencies-nested-extras.test
  tests/installation/fixtures/with-dependencies.test
  tests/installation/fixtures/with-directory-dependency-poetry-transitive.test
  tests/installation/fixtures/with-directory-dependency-poetry.test
  tests/installation/fixtures/with-directory-dependency-setuptools.test
  tests/installation/fixtures/with-duplicate-dependencies-update.test
  tests/installation/fixtures/with-duplicate-dependencies.test
  tests/installation/fixtures/with-file-dependency-transitive.test
  tests/installation/fixtures/with-file-dependency.test
  tests/installation/fixtures/with-multiple-updates.test
  tests/installation/fixtures/with-optional-dependencies.test
  tests/installation/fixtures/with-platform-dependencies.test
  tests/installation/fixtures/with-prereleases.test
  tests/installation/fixtures/with-pypi-repository.test
  tests/installation/fixtures/with-python-versions.test
  tests/installation/fixtures/with-same-version-url-dependencies.test
  tests/installation/fixtures/with-sub-dependencies.test
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/fixtures/with-vcs-dependency-with-extras.test
  tests/installation/fixtures/with-vcs-dependency-without-ref.test
  tests/installation/fixtures/with-wheel-dependency-no-requires-dist.test
  tests/installation/test_installer.py
  tests/installation/test_installer_old.py
  tests/packages/test_locker.py
Labels: area/solver, kind/refactor

#6615 provider: fetch optional vcs dependency only if required
  src/poetry/puzzle/provider.py
  tests/puzzle/test_provider.py
Labels: area/solver, kind/enhancement, impact/changelog

#6557 docs: rephrase plugin configuration in docs
  docs/plugins.md
  docs/pyproject.md
Labels: area/docs, impact/backport, impact/docs, backport/1.2

#6618 ci: define `timeout` on macOS
  .github/workflows/main.yml
Labels: area/ci, impact/backport, backport/1.2

#6628 fix(env): run Python inside environments in isolated mode
  src/poetry/utils/env.py
Labels: kind/bug, area/venv, impact/changelog
