Repository python-poetry/poetry, pull requests merged in 2022-06, with the labels that each got.

#5158 update pyproject readme docs
  docs/pyproject.md
Labels: Documentation, Awaiting Reponse

#4280 Update _index.md
  docs/_index.md
Labels: Documentation, Awaiting Reponse

#5708 docs: Improve contributing docs
  CONTRIBUTING.md
  docs/contributing.md
Labels: Documentation

#5452 All extras
  docs/cli.md
  docs/pyproject.md
  src/poetry/console/commands/install.py
  tests/console/commands/test_install.py
Labels: CLI

#5647 Add hook to update io.input.stream to sys.stdin if it is None.
  tests/console/commands/cache/__init__.py
  tests/console/commands/cache/conftest.py
  tests/console/commands/cache/test_clear.py
  tests/console/commands/cache/test_list.py
Labels: CLI, Upstream Issue, Dependency

#4122 Use `safe_extra` to standardize extra dependencies
  src/poetry/puzzle/provider.py
  src/poetry/utils/helpers.py
  tests/console/commands/test_add.py
  tests/installation/fixtures/with-dependencies-nested-extras.test
  tests/installation/test_installer.py
  tests/utils/test_helpers.py
Labels: Awaiting Reponse

#5809 Fix the wrong key and URL of adding publishable repositories in documetation
  docs/repositories.md
Labels: Documentation

#5816 Fix typo
  docs/cli.md
Labels: Documentation

#5815 Add link to "Dependency specification" in `pyproject.toml` reference
  docs/pyproject.md
Labels: Documentation

#5845 fixed small spelling mistake
  docs/repositories.md
Labels: Documentation

#5857 Update installation and update docs
  docs/_index.md
  docs/plugins.md
Labels: Documentation

#5874 Better document exact requirement specification
  docs/cli.md
  docs/dependency-specification.md
Labels: Documentation

#5822 docs: Add paragraph about @ operator
  docs/cli.md
  docs/dependency-specification.md
Labels: Documentation

#5879 Rework completions section in docs
  docs/_index.md
Labels: Documentation

#5884 Clarifying `scripts` section in docs
  docs/pyproject.md
Labels: Documentation
