Repository python-poetry/poetry, pull requests merged in 2023-03, with the labels that each got.

#7579 fix: properly get and install the dependencies for an editable build
  src/poetry/installation/chef.py
Labels: area/installer, impact/backport, impact/changelog, backport/1.4

#7563 docs: clarify behavior of --extras and subcommands
  docs/pyproject.md
Labels: area/docs, impact/backport, backport/1.4

#7580 fix: append subdirectory to archive path (#7575)
  src/poetry/installation/executor.py
  tests/installation/test_executor.py
Labels: area/installer, impact/backport, backport/1.4

#7594 Fix certain hash miss matches in case of non weel installations
  src/poetry/installation/chef.py
  src/poetry/installation/executor.py
  tests/installation/test_chef.py
  tests/installation/test_executor.py
Labels: area/installer, impact/backport, impact/changelog, backport/1.4

#7613 [docs] Offer workaround for the cases where Poetry is downloading
  docs/faq.md
Labels: area/docs, impact/backport, impact/docs, backport/1.4

#7626 add missing env keyword in Env._run
  src/poetry/utils/env.py
Labels: impact/backport, backport/1.4

#7671 installer 0.7.0
  poetry.lock
  pyproject.toml
  src/poetry/installation/wheel_installer.py
  tests/fixtures/distributions/demo-0.1.2-py2.py3-none-any.whl
  tests/repositories/fixtures/pypi.org/dists/pytest-3.5.1-py2.py3-none-any.whl
Labels: area/installer, impact/backport, backport/1.4

#7676 chore: update poetry-core
  poetry.lock
  pyproject.toml
Labels: impact/backport, backport/1.4

#7666 installer: fix optimization level
  src/poetry/installation/wheel_installer.py
  tests/installation/test_wheel_installer.py
Labels: area/installer, impact/backport, backport/1.4

#7667 installer: improve error messages for building dependencies
  src/poetry/installation/executor.py
  tests/fixtures/build_system_requires_not_available/README.rst
  tests/fixtures/build_system_requires_not_available/pyproject.toml
  tests/fixtures/build_system_requires_not_available/simple_project/__init__.py
  tests/installation/test_executor.py
Labels: area/installer, impact/backport, backport/1.4

#7017 Correctly parse Git submodule URLs
  src/poetry/vcs/git/backend.py
  tests/integration/test_utils_vcs_git.py
Labels: impact/backport, area/vcs, backport/1.4

#7699 remove stdout=subprocess.PIPE from env._call, see #7698
  src/poetry/utils/env.py
  tests/utils/test_env.py
Labels: area/installer, impact/backport, backport/1.4

#7694 installer: do not fail on invalid wheels, print only a warning
  src/poetry/installation/executor.py
  src/poetry/installation/wheel_installer.py
  tests/fixtures/distributions/demo_invalid_record-0.1.0-py2.py3-none-any.whl
  tests/fixtures/distributions/demo_invalid_record2-0.1.0-py2.py3-none-any.whl
  tests/installation/test_executor.py
  tests/utils/test_cache.py
Labels: area/installer, impact/backport, backport/1.4
