Repository python-poetry/poetry, pull requests merged in 2023-02, with the labels that each got.

#7468 chore: remove deprecated repository modules
  src/poetry/repositories/__init__.py
  src/poetry/repositories/cached.py
  src/poetry/repositories/http.py
  src/poetry/repositories/pool.py
  tests/installation/test_executor.py
Labels: kind/refactor, impact/changelog, impact/deprecation

#7520 Fix year in changelog
  CHANGELOG.md
Labels: impact/backport, backport/1.3

#7503 (📚) Mention the different types of exact specifications and pep440
  docs/dependency-specification.md
Labels: area/docs, impact/docs
