Repository python-poetry/poetry, pull requests merged in 2023-01, with the labels that each got.

#7266 fix: as_uri() can only be applied to an absolute path
  src/poetry/masonry/builders/editable.py
Labels: backport/1.3

#7236 PEP 440 pre-release handling - part 2
  src/poetry/console/commands/show.py
  src/poetry/repositories/repository.py
  tests/puzzle/test_provider.py
Labels: area/solver, impact/changelog

#7286 Add clarifications for `virtualenvs.path` settings
  docs/configuration.md
Labels: area/docs, impact/backport, impact/docs, backport/1.3

#7290 ci: update skip job for 3.11 GA
  .github/workflows/skip.yml
Labels: area/ci, impact/backport, backport/1.3

#7288 docs: update for get-poetry.py removal
  docs/_index.md
Labels: area/docs, impact/backport, impact/docs, backport/1.3

#7318 Fix: Missing bash key formatter in code block
  docs/_index.md
Labels: area/docs, impact/docs

#6902 Add Python 3.11 to CirrusCI config
  .cirrus.yml
Labels: area/ci

#7241 poetry check command accepts --directory argument
  src/poetry/console/commands/check.py
  tests/console/commands/test_check.py
Labels: backport/1.3

#7390 Bump dulwich to 0.21.
  poetry.lock
  pyproject.toml
Labels: area/project/deps

#7387 remove strange VENDORS handling in installed repository
  src/poetry/repositories/installed_repository.py
  tests/repositories/test_installed_repository.py
Labels: kind/refactor

#7386 remove empty vendor directory
  src/poetry/_vendor/.gitignore
Labels: kind/refactor

#7389 Don't uninstall packages that should be kept
  src/poetry/puzzle/transaction.py
  tests/puzzle/test_transaction.py
Labels: kind/bug, area/installer, area/deps

#7434 fix(dependencies): remove upper boundary for importlib-metadata
  poetry.lock
  pyproject.toml
Labels: area/project/deps
