Repository python-poetry/poetry, pull requests merged in 2024-03, with the labels that each got.

#9074 doc: mention interactive credential configuration
  docs/repositories.md
Labels: area/docs, impact/docs

#9082 lazy-wheel: be more robust with regard to Artifactory's incorrect handling of range requests with negative offsets
  src/poetry/inspection/lazy_wheel.py
  tests/inspection/test_lazy_wheel.py
Labels: backport/1.8

#9084 lazy-wheel: improve handling of servers that tell us that they support range requests but do not respect them
  src/poetry/inspection/lazy_wheel.py
  tests/inspection/test_lazy_wheel.py
Labels: backport/1.8

#9087 lazy-wheel: allow redirects for HEAD request
  src/poetry/inspection/lazy_wheel.py
  tests/inspection/test_lazy_wheel.py
Labels: backport/1.8

#9049 Hash metadata as bytes
  src/poetry/repositories/http_repository.py
Labels: backport/1.8

#9098 doc: add notes for advanced installation steps
  docs/_index.md
Labels: area/docs, impact/docs

#9107 ci/gha: simplify poetry setup and caching
  .github/workflows/docs.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: status/needs-consensus

#9110 docs/publish: add ref to configuring credentials
  docs/cli.md
Labels: area/docs, impact/docs

#9088 cli/new: support interactive config
  docs/cli.md
  src/poetry/console/commands/init.py
  src/poetry/console/commands/new.py
  src/poetry/layouts/layout.py
  tests/console/commands/conftest.py
  tests/console/commands/test_init.py
  tests/console/commands/test_new.py
Labels: area/cli

#9121 doc/repos: add hint for env var url config
  docs/repositories.md
Labels: area/docs, impact/docs

#9127 ci: lock threads only once daily
  .github/workflows/lock-threads.yml
Labels: area/ci

#9118 cli/env: handle removal of in-project venv
  docs/managing-environments.md
  src/poetry/console/commands/env/remove.py
  src/poetry/utils/_compat.py
  tests/console/commands/env/conftest.py
  tests/console/commands/env/test_remove.py
Labels: area/cli, area/docs, impact/docs

#9138 Add example for dependency with multiple extras
  docs/pyproject.md
Labels: impact/docs

#9176 ci: ensure test fixtures are generated
  .github/workflows/tests-ensure-fixtures.yml
Labels: area/ci

#9207 env: add support for untagged CPython builds ...
  src/poetry/utils/env/script_strings.py
  src/poetry/utils/env/system_env.py
  tests/utils/env/test_system_env.py
Labels: area/solver, kind/enhancement

#9209 tests: replace mock_download with httpretty mock
  tests/conftest.py
  tests/console/commands/test_add.py
  tests/console/commands/test_show.py
  tests/helpers.py
  tests/installation/fixtures/with-same-version-url-dependencies.test
  tests/installation/fixtures/with-url-dependency.test
  tests/installation/test_installer.py
  tests/packages/test_direct_origin.py
  tests/packages/test_locker.py
  tests/puzzle/test_solver.py
  tests/repositories/fixtures/installed/lib/python3.7/site-packages/url_pep_610-1.2.3.dist-info/direct_url.json
  tests/repositories/fixtures/python_hosted.py
  tests/repositories/test_installed_repository.py
  tests/utils/test_cache.py
  tests/utils/test_dependency_specification.py
Labels: area/testing, kind/enhancement

#9211 tests: remove unnecessary http.disable() calls
  tests/console/commands/test_check.py
  tests/console/commands/test_lock.py
Labels: area/testing

#9213 doc/faq: remove misleading wording around venvs
  docs/faq.md
Labels: area/docs, impact/docs

#9224 [1.8 backport] ci/gha: simplify poetry setup and caching
  .github/workflows/docs.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: area/ci

#9218 [1.8 backport] env: add support for untagged CPython builds ...
  src/poetry/utils/env/script_strings.py
  src/poetry/utils/env/system_env.py
  tests/utils/env/test_system_env.py
Labels: area/solver, kind/enhancement

#9232 ci: enable merge queues
  .github/workflows/backport.yaml
  .github/workflows/tests.yaml
Labels: area/ci

#9241 ci: fix matrix skip logic
  .github/workflows/tests.yaml
Labels: area/ci

#9243 ci/docs: fix relative workflow path
  .github/workflows/docs.yaml
Labels: area/docs, area/ci, impact/docs
